new1/Models/Model1.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace new1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class catEntities : DbContext
    {
        public catEntities()
            : base("name=catEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<record1> record1 { get; set; }
        public virtual DbSet<record2> record2 { get; set; }
    }
}

new1/Models/Model1.Designer.cs
// T4 code generation is enabled for model 'D:\kaushal\new1\new1\Models\Model1.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

new1/Models/Model1.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

new1/Models/record1.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace new1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class record1
    {
        public int id { get; set; }
        public string name { get; set; }
        public string address { get; set; }
    }
}

new1/Models/record2.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace new1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class record2
    {
        public int id { get; set; }
        public string name { get; set; }
        public string address { get; set; }
    }
}

new1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace new1.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

new1/Controllers/appleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using new1.Models;

namespace new1.Controllers
{
    public class appleController : Controller
    {
        catEntities db = new catEntities();

        // GET: apple
        public ActionResult kaushal()
        {
            List<record1> all_data = db.record1.ToList();
            return View(all_data);
        }
        public ActionResult Create()
        {
            return View();
        }
        public ActionResult SaveData(record1 record1)

        {
            db.record1.Add(record1);
            db.SaveChanges();
            return RedirectToAction("kaushal");
        }
        public ActionResult Edit(int id)
        {
            record1 data = db.record1.Find(id);
            //record1 data = db.employee.FirstorDefault(x=)
            return View(data);
        }
        public ActionResult UpdateData(record1 record1)
        {
            record1 update = db.record1.Find(record1.id);
            update.name = record1.name;
            update.address = record1.address;
            db.Entry(update).State = System.Data.Entity.EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("kaushal");

        }

    }
}

new1/Controllers/record2Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using new1.Models;

namespace new1.Controllers
{
    public class record2Controller : Controller
    {
        catEntities db = new catEntities();

        // GET: record2
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Create()
        {
            List<record2> all_data = db.record2.ToList();
            return View();
        }
        public ActionResult SaveData(new1.Models.record2 record2)

        {
            db.record2.Add(record2);
            db.SaveChanges();
            return RedirectToAction("kaushal");
        }
        public ActionResult Edit(int id)
        {
            record2 data = db.record2.Find(id);
            //record2 data = db.employee.FirstorDefault(x=)
            return View(data);
        }
        public ActionResult UpdateData(record2 record2)
        {
            record1 update = db.record1.Find(record2.id);
            update.name = record2.name;
            update.address = record2.address;
            db.Entry(update).State = System.Data.Entity.EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("kaushal");

        }

    }
}

new1/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

new1/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

new1/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

new1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Table", "kaushal", "apple")</li>
                   <li>@Html.ActionLink("Add record", "Create", "apple")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

new1/Views/apple/create.cshtml
@{
    ViewBag.Title = "create";
}

<h2>create</h2>
<form action="SaveData">
    <label class="col-md-2">ID</label>
    <div class="col-md-4">
        <input type="text" name="id" class="form-control" />
    </div>

    <label class="col-md-2">Name</label>
    <div class="col-md-4">
        <input type="text" name="name" class="form-control" />
    </div>

    <label class="col-md-2">Address</label>
    <div class="col-md-4">
        <input type="text" name="address" class="form-control" />
    </div>

    <input type="submit" name="submit" class="submitButton" />

    <br /><br /><br />

    <label class="col-md-2">ID</label>
    <div class="col-md-4">
        <input type="text" name="id" class="form-control" />
    </div>

    <label class="col-md-2">Name</label>
    <div class="col-md-4">
        <input type="text" name="name" class="form-control" />
    </div>

    <label class="col-md-2">Address</label>
    <div class="col-md-4">
        <input type="text" name="address" class="form-control" />
    </div>

    <input type="submit" name="submit" class="submitButton" />
</form>

new1/Views/apple/edit.cshtml
@model new1.Models.record1



@{
    ViewBag.Title = "Edit";
}

<h2>create</h2>
@using (Html.BeginForm("UpdateData", "apple"))
{
<input type="hidden" name="id" class="form-ciontrol" value="@(Model.id)" />


<label class="col-md-2">Name</label>
<div class="col-md-4">
    <input type="text" name="name" class="form-control" value="@(Model.name)" />
</div>

<label class="col-md-2">Address</label>
<div class="col-md-4">
    <input type="text" name="address" class="form-control" value="@(Model.address)" />
</div>

<input type="submit" name="submit" class="submitButton" />

}

new1/Views/apple/kaushal.cshtml
@model List<new1.Models.record1>
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
<table class="table" border="1">
     <tr>
         <th>Id</th>
         <th>Name</th>
         <th>Address</th>
         <th>Edit name</th>
     </tr>
    @foreach (var data in Model)
    {
<tr>
    <td>@(data.id)</td>
    <td>@(data.name)</td>
    <td>@(data.address)</td>
    <td><a href="@Url.Action("Edit", new { id = data.id })">Edit</a></td>
</tr>
    }
</table>
<button class="btn btn-sucess"><a href="@Url.Action("Create")">Add record</a></button>